### ISSUE TITLE
latest will not start

### ISSUE THREAD

**Issue by marafa** [packetworks/docker-nxfilter#14]
the latest image will not start. i run it like so (unusual ports as i have other things running on the standard ports)
` docker run -dt --name nxfilter -v /opt/nxfilter-base/nxfilter-conf:/nxfilter/conf -v /opt/nxfilter-base/nxfilter-log:/nxfilter/log -v /opt/nxfilter-base/nxfilter-db:/nxfilter/db -p 7180:80 -p 7443:443 -p 53:53/udp -p 19002-19004:19002-19004 --restart always packetworks/nxfilter-base:latest`

broke with

```
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.p.run(Unknown Source)
```

**Comment by marafa** [comment]
rebuilt it locally and got the same error

**Comment by marafa** [comment]
the local volume mapping to /nxfilter/conf must be prepopulated before running the container

**Comment by cron410** [comment]
Yep, @dgibbs64 has included them in his commits. I'll be pulling the fixes in today.

**Comment by cron410** [comment]
You're right. If you want to use folder bind mounts, you need to copy the contents of your DB etc to that folder. It works great with docker volumes though.
