### ISSUE TITLE
Java Exception

### ISSUE THREAD

**Issue by cron410** [packetworks/docker-nxfilter#7]
When running the container either detached or interactive, I get a java exception. 

Exception in thread "main" java.lang.NullPointerException
        at nxd.Main.<init>(Unknown Source)
        at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
        at nxd.o.run(Unknown Source)

**Comment by cron410** [comment]
Looks like this only happens when using problematic volumes where the application cannot write DB, config, or log files.
